import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layout/Navbar";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { EdgeStoreProvider } from "@/lib/edgestore";
import {Toaster} from 'react-hot-toast'
import { ThemeProvider } from "next-theme";
import { SocketContextProvider } from "@/context/SocketContext";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '700']
});


export const metadata: Metadata = {
  title: "Web dev Blog",
  description: "Generated by create next app",
  icons: { icon : '/logo.svg'}
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//  creating session for users
  const session = await auth()

  return (
    <EdgeStoreProvider>
    <SessionProvider session={session}>
      <SocketContextProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn('antialiased flex flex-col min-h-screen px-2', poppins.variable)}
      > 
      <Toaster
        position="bottom-center"
        toastOptions={{
          style: {
            background: "rgb(51 65 85)",
            color: "#fff"
          }
        }}
      />
      {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange> */}
        <Navbar />
        <main className="flex-grow">

          {children}
        </main>
        <footer>Footer</footer>
      {/* </ThemeProvider> */}
      </body>
    </html>
    </SocketContextProvider>
  </SessionProvider>
  </EdgeStoreProvider> 
  );
}
