import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layout/Navbar";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '700']
});


export const metadata: Metadata = {
  title: "Web dev Blog",
  description: "Generated by create next app",
  icons: { icon : '/logo.svg'}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('antialiased flex flex-col min-h-screen px-2', poppins.variable)}
      > 
      
        <Navbar />
        <main className="flex-grow">

          {children}
        </main>
        <footer>Footer</footer>
    
      </body>
    </html>
  );
}
