import { Metadata } from 'next';
import React from 'react'

//add MetaData for our login and register layout
export const metadata: Metadata = {
  title: "AuthRegister/Login",
  description: "Generated by create next app",
  icons: { icon : '/logo.svg'}
};

//create a props
const AuthLayout = ({children} : Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div>
      layout
        {/* <nav>AuthNav</nav>
        {children} */}
    </div>
  )
}

export default AuthLayout